nodeLinker: pnp

packageExtensions:
  "@typescript-eslint/eslint-plugin@*":
    dependencies:
      "@typescript-eslint/parser": "*"
  "eslint-config-next@*":
    dependencies:
      "next": "*"
      "react": "*"
      "react-dom": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.6.1.cjs
