import { AppLayout } from '@/components/AppLayout';
import './globals.css';
import '@tech-frontier/ui-desktop/style.css';
import type { Metadata } from 'next';

// NOTE: https://nextjs.org/docs/app/building-your-application/optimizing/metadata
export const metadata: Metadata = {
  title: 'Trendy Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <AppLayout>
          {children}
        </AppLayout>
      </body>
    </html>
  );
}
