#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get the current branch name
branch_name=$(git rev-parse --symbolic-full-name HEAD)

# If the current branch is main, print an error message
if [[ $branch_name == "refs/heads/fix/main-pre-push" ]]; then
  echo "You are currently on the main branch. Please switch to a different branch."
  exit 1
fi
